executable_file = windows_2
c_file = /home/gihad/Documents/ncurses_examples/windows_2/windows_2.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu

# run:	
	./$(executable_file) 	
# clean:	
	rm $(executable_file)
