executable_file = create_window
c_file = /home/gihad/Documents/ncurses_examples/create_window/create_window.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu

# run:	
	./$(executable_file) 
	
# clean:	
	rm $(executable_file)
