executable_file = forms_library_1_test
c_file = /home/gihad/Documents/ncurses_examples/forms_library_1_test/forms_library_1_test.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu -lpanel 

# run:	
	./$(executable_file) 	
# clean:	
	rm $(executable_file)
