executable_file = Miscellaneous_features_1
c_file = /home/gihad/Documents/ncurses_examples/Miscellaneous_features_1/Miscellaneous_features_1.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu

# run:	
	./$(executable_file) 	
# clean:	
	rm $(executable_file)
