executable_file = panel_library_2
c_file = /home/gihad/Documents/ncurses_examples/panel_library_2/panel_library_2.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu -lpanel 

# run:	
	./$(executable_file) 	
# clean:	
	rm $(executable_file)
