executable_file = hello_world_and_initialisation
c_file = /home/gihad/Documents/ncurses_examples/hello_world_and_initialisation/hello_world_and_initialisation.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)
