executable_file = input_functions
c_file = /home/gihad/Documents/ncurses_examples/input_functions/input_functions.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)
