executable_file = keypad_function_explain
c_file = /home/gihad/Documents/ncurses_examples/keypad_function_explain/keypad_function_explain.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)
