executable_file = output_functions
c_file = /home/gihad/Documents/ncurses_examples/output_functions/output_functions.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)
