executable_file = keyboard
c_file = /home/gihad/Documents/ncurses_examples/keyboard/keyboard.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu

# run:	
	./$(executable_file) 	
# clean:	
	rm $(executable_file)
