executable_file = menu_library_5
c_file = /home/gihad/Documents/ncurses_examples/menu_library_5/menu_library_5.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu -lpanel 

# run:	
	./$(executable_file) 	
# clean:	
	rm $(executable_file)
