executable_file = screen_manipulation
c_file = /home/gihad/Documents/ncurses_examples/screen_manipulation/screen_manipulation.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu

# run:	
	./$(executable_file) 	
# clean:	
	rm $(executable_file)
