executable_file = attributes_2
c_file = /home/gihad/Documents/ncurses_examples/attributes_2/attributes_2.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu

# run:	
	./$(executable_file) argv_1.text argv_2.text
	
# clean:	
	rm $(executable_file)
