executable_file = windows_1
c_file = /home/gihad/Documents/ncurses_examples/windows_1/windows_1.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu

# run:	
	./$(executable_file) 
	
# clean:	
	rm $(executable_file)
