executable_file = color
c_file = /home/gihad/Documents/ncurses_examples/color/color.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu

# run:	
	./$(executable_file) 	
# clean:	
	rm $(executable_file)
