executable_file = menu_library_3_test
c_file = /home/gihad/Documents/ncurses_examples/menu_library_3_test/menu_library_3_test.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses -lmenu -lpanel 

# run:	
	./$(executable_file) 	
# clean:	
	rm $(executable_file)
